### ISSUE TITLE
打包后转换 rem 方案

### ISSUE THREAD

**Issue by cloudfroster** [bailichen/ImitateWeixinApp#17]
目前代码里是在写的时候用的插件自动转换为 rem 的么。感觉看起来样式代码很乱。
考虑下用 post2rem 在打包的时候处理点好。
代码写成
```css
{
  width: 44px;
}
```
然后打包后转换为 rem 好点。

这个 rem 自适应方案说起来还蛮久了。其实可以考虑直接用 flex 布局。

代码格式还是有点乱，估计是因为没有用 eslint 吧。

文件组件形式蛮喜欢的

**Comment by bailichen** [comment]
代码是rem和flex布局结合写的，rem值是sublime的插件自动转化的，小数点后面的位数控制的比较长

**Comment by cloudfroster** [comment]
嗯 就是比如我没有安装 sublime 转换的插件，就写不了，需要自己写，所以很麻烦，让 postcss 来自动计算比较好点，不过目前你的代码已经写了这么多了，改起来也麻烦。

**Comment by bailichen** [comment]
嗯  你可以下载个插件放在sublime里也可以    不过用flex布局了之后 用px或者rem都不影响的

**Comment by bailichen** [comment]
你说的postcss 也是个好方法
