### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zheng521** [bailichen/ImitateWeixinApp#27]
请问下 你这个项目里的iscroll 是在哪里引用了，是怎么解决 聊天框最底部那个 position:fixed 的问题的呢？

**Comment by bailichen** [comment]
iscroll没有用，之前用感觉有点问题，就没用了，滚动是自带的滚动

**Comment by zheng521** [comment]
那看你这个项目里 聊天窗口 并没有出现那个 position:fixed 的问题，你有注意到这个问题么？就是在ios 上不识别这个fixe的属性

**Comment by bailichen** [comment]
不是不识别fixed，而是absolute 的父级如果没有relative的情况下会变成固定定位

**Comment by zheng521** [comment]
明白了，多谢
